# Generated by Django 5.1.5 on 2025-02-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_worker_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ["name"]},
        ),
    ]
