# Generated by Django 5.1.5 on 2025-02-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_position_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worker",
            options={"ordering": ["username"]},
        ),
    ]
