# Generated by Django 5.1.5 on 2025-02-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["priority", "deadline"]},
        ),
    ]
