# Generated by Django 5.1.5 on 2025-02-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed", "priority", "deadline"]},
        ),
    ]
