# Generated by Django 5.1.5 on 2025-02-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tasktype",
            options={"ordering": ["name"]},
        ),
    ]
